FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# copio los proyectos necesarios para mi worker
COPY ["MovilidadInteligente.Worker/MovilidadInteligente.Worker.csproj", "MovilidadInteligente.Worker/"]
COPY ["MovilidadInteligente.Application/MovilidadInteligente.Application.csproj", "MovilidadInteligente.Application/"]
COPY ["MovilidadInteligente.Infrastructure/MovilidadInteligente.Infrastructure.csproj", "MovilidadInteligente.Infrastructure/"]
COPY ["MovilidadInteligente.Domain/MovilidadInteligente.Domain.csproj", "MovilidadInteligente.Domain/"]

RUN dotnet restore "MovilidadInteligente.Worker/MovilidadInteligente.Worker.csproj"

COPY . .
WORKDIR "/src/MovilidadInteligente.Worker"
RUN dotnet build "MovilidadInteligente.Worker.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MovilidadInteligente.Worker.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MovilidadInteligente.Worker.dll"]