FROM quay.io/keycloak/keycloak:latest

COPY keycloak-realm.json /opt/keycloak/data/import/realm.json
COPY create-user.sh /opt/keycloak/create-user.sh

USER root
RUN chmod +x /opt/keycloak/create-user.sh

ENTRYPOINT ["/bin/bash", "-c", "\
/opt/keycloak/bin/kc.sh start-dev --import-realm & \
sleep 25 && \
/opt/keycloak/create-user.sh && \
wait"]