services:
  # Base de Datos (SQL Server)
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: movilidad_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: always

  # Broker IoT (Mosquitto)
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: movilidad_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  # Keycloak (SSO)
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile.Keycloak
    container_name: movilidad_sso
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    restart: always

  proxy_api:
    image: nginx:alpine
    container_name: movilidad_proxy_api
    ports:
      # nginx toma el puerto 5150 que antes usaba la api directamente
      - "5150:80"
    volumes:
      - ./nginx-balancer.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile.API
    depends_on:
      - sqlserver
      - keycloak
    restart: always

  worker:
    container_name: movilidad_worker
    build:
      context: .
      dockerfile: Dockerfile.Worker
    depends_on:
      - sqlserver
      - mosquitto
    restart: always
  
  frontend:
    image: nginx:alpine
    container_name: movilidad_frontend
    ports:
      - "80:80" 
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    restart: always
  simulador:
    container_name: movilidad_simulador
    build:
      context: .
      dockerfile: Dockerfile.Simulador
    environment:
      - API_URL=http://proxy_api:80/api/vehiculos
    depends_on:
      - sqlserver
      - api
      - mosquitto
    restart: always

volumes:
  mssql_data: