events { 
    worker_connections 1024; 
}

http {
    # defino el grupo de servidores de mi api
    # docker compose enviara el trafico en round-robin automaticamente
    upstream api_backend {
        server api:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://api_backend;
            
            # configuraciones criticas para que signalr y websockets funcionen a traves del proxy
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
            # paso la informacion real del cliente a mi api
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}