// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovilidadInteligente.Infrastructure.Data;

#nullable disable

namespace MovilidadInteligente.Infrastructure.Migrations
{
    [DbContext(typeof(MovilidadDbContext))]
    [Migration("20260512064538_AddPagos")]
    partial class AddPagos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.Coordenada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("RutaPredeterminadaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RutaPredeterminadaId");

                    b.ToTable("Coordenadas");
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.HistorialViaje", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("CostoEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DestinoLocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("DistanciaKm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FinUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InicioUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 5, 12, 6, 45, 37, 736, DateTimeKind.Utc).AddTicks(8399));

                    b.Property<string>("OrigenLocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VehiculoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DestinoLocationId");

                    b.HasIndex("OrigenLocationId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("HistorialViajes");
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.Pago", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("HistorialViajeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("MXN");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("HistorialViajeId");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.RutaPredeterminada", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DestinoLocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NivelTraficoActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrigenlocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DestinoLocationId");

                    b.HasIndex("OrigenlocationId");

                    b.ToTable("RutasPredeterminadas");
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.Ubicacion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.Vehiculo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Combustible")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UltimaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 5, 12, 6, 45, 37, 736, DateTimeKind.Utc).AddTicks(1502));

                    b.HasKey("Id");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.Coordenada", b =>
                {
                    b.HasOne("MovilidadInteligente.Domain.Entities.RutaPredeterminada", "RutaPredeterminada")
                        .WithMany("Coordenadas")
                        .HasForeignKey("RutaPredeterminadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RutaPredeterminada");
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.HistorialViaje", b =>
                {
                    b.HasOne("MovilidadInteligente.Domain.Entities.Ubicacion", "DestinoLocation")
                        .WithMany()
                        .HasForeignKey("DestinoLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovilidadInteligente.Domain.Entities.Ubicacion", "OrigenLocation")
                        .WithMany()
                        .HasForeignKey("OrigenLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovilidadInteligente.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinoLocation");

                    b.Navigation("OrigenLocation");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.Pago", b =>
                {
                    b.HasOne("MovilidadInteligente.Domain.Entities.HistorialViaje", "HistorialViaje")
                        .WithMany()
                        .HasForeignKey("HistorialViajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Pagos_HistorialViajes");

                    b.Navigation("HistorialViaje");
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.RutaPredeterminada", b =>
                {
                    b.HasOne("MovilidadInteligente.Domain.Entities.Ubicacion", "DestinoLocation")
                        .WithMany()
                        .HasForeignKey("DestinoLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovilidadInteligente.Domain.Entities.Ubicacion", "OrigenlLocation")
                        .WithMany()
                        .HasForeignKey("OrigenlocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinoLocation");

                    b.Navigation("OrigenlLocation");
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.RutaPredeterminada", b =>
                {
                    b.Navigation("Coordenadas");
                });
#pragma warning restore 612, 618
        }
    }
}
