// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovilidadInteligente.Infrastructure.Data;

#nullable disable

namespace MovilidadInteligente.Infrastructure.Migrations
{
    [DbContext(typeof(MovilidadDbContext))]
    [Migration("20260512071942_AddInserts")]
    partial class AddInserts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.Coordenada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("RutaPredeterminadaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RutaPredeterminadaId");

                    b.ToTable("Coordenadas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitud = 27.071999999999999,
                            Longitud = -109.443,
                            Orden = 1,
                            RutaPredeterminadaId = "R1"
                        },
                        new
                        {
                            Id = 2,
                            Latitud = 27.077999999999999,
                            Longitud = -109.446,
                            Orden = 2,
                            RutaPredeterminadaId = "R1"
                        },
                        new
                        {
                            Id = 3,
                            Latitud = 27.085000000000001,
                            Longitud = -109.45,
                            Orden = 3,
                            RutaPredeterminadaId = "R1"
                        },
                        new
                        {
                            Id = 4,
                            Latitud = 27.071999999999999,
                            Longitud = -109.443,
                            Orden = 1,
                            RutaPredeterminadaId = "R2"
                        },
                        new
                        {
                            Id = 5,
                            Latitud = 27.074000000000002,
                            Longitud = -109.44,
                            Orden = 2,
                            RutaPredeterminadaId = "R2"
                        },
                        new
                        {
                            Id = 6,
                            Latitud = 27.077999999999999,
                            Longitud = -109.44199999999999,
                            Orden = 3,
                            RutaPredeterminadaId = "R2"
                        },
                        new
                        {
                            Id = 7,
                            Latitud = 27.082000000000001,
                            Longitud = -109.447,
                            Orden = 4,
                            RutaPredeterminadaId = "R2"
                        },
                        new
                        {
                            Id = 8,
                            Latitud = 27.085000000000001,
                            Longitud = -109.45,
                            Orden = 5,
                            RutaPredeterminadaId = "R2"
                        },
                        new
                        {
                            Id = 9,
                            Latitud = 27.071999999999999,
                            Longitud = -109.443,
                            Orden = 1,
                            RutaPredeterminadaId = "R3"
                        },
                        new
                        {
                            Id = 10,
                            Latitud = 27.065999999999999,
                            Longitud = -109.441,
                            Orden = 2,
                            RutaPredeterminadaId = "R3"
                        },
                        new
                        {
                            Id = 11,
                            Latitud = 27.059999999999999,
                            Longitud = -109.44,
                            Orden = 3,
                            RutaPredeterminadaId = "R3"
                        },
                        new
                        {
                            Id = 12,
                            Latitud = 27.071999999999999,
                            Longitud = -109.443,
                            Orden = 1,
                            RutaPredeterminadaId = "R4"
                        },
                        new
                        {
                            Id = 13,
                            Latitud = 27.07,
                            Longitud = -109.438,
                            Orden = 2,
                            RutaPredeterminadaId = "R4"
                        },
                        new
                        {
                            Id = 14,
                            Latitud = 27.065000000000001,
                            Longitud = -109.437,
                            Orden = 3,
                            RutaPredeterminadaId = "R4"
                        },
                        new
                        {
                            Id = 15,
                            Latitud = 27.062000000000001,
                            Longitud = -109.43899999999999,
                            Orden = 4,
                            RutaPredeterminadaId = "R4"
                        },
                        new
                        {
                            Id = 16,
                            Latitud = 27.059999999999999,
                            Longitud = -109.44,
                            Orden = 5,
                            RutaPredeterminadaId = "R4"
                        },
                        new
                        {
                            Id = 17,
                            Latitud = 27.085000000000001,
                            Longitud = -109.45,
                            Orden = 1,
                            RutaPredeterminadaId = "R5"
                        },
                        new
                        {
                            Id = 18,
                            Latitud = 27.077999999999999,
                            Longitud = -109.435,
                            Orden = 2,
                            RutaPredeterminadaId = "R5"
                        },
                        new
                        {
                            Id = 19,
                            Latitud = 27.07,
                            Longitud = -109.42,
                            Orden = 3,
                            RutaPredeterminadaId = "R5"
                        },
                        new
                        {
                            Id = 20,
                            Latitud = 27.085000000000001,
                            Longitud = -109.45,
                            Orden = 1,
                            RutaPredeterminadaId = "R6"
                        },
                        new
                        {
                            Id = 21,
                            Latitud = 27.082999999999998,
                            Longitud = -109.44499999999999,
                            Orden = 2,
                            RutaPredeterminadaId = "R6"
                        },
                        new
                        {
                            Id = 22,
                            Latitud = 27.079999999999998,
                            Longitud = -109.44,
                            Orden = 3,
                            RutaPredeterminadaId = "R6"
                        },
                        new
                        {
                            Id = 23,
                            Latitud = 27.074999999999999,
                            Longitud = -109.43000000000001,
                            Orden = 4,
                            RutaPredeterminadaId = "R6"
                        },
                        new
                        {
                            Id = 24,
                            Latitud = 27.07,
                            Longitud = -109.42,
                            Orden = 5,
                            RutaPredeterminadaId = "R6"
                        },
                        new
                        {
                            Id = 25,
                            Latitud = 27.059999999999999,
                            Longitud = -109.44,
                            Orden = 1,
                            RutaPredeterminadaId = "R7"
                        },
                        new
                        {
                            Id = 26,
                            Latitud = 27.065000000000001,
                            Longitud = -109.45,
                            Orden = 2,
                            RutaPredeterminadaId = "R7"
                        },
                        new
                        {
                            Id = 27,
                            Latitud = 27.07,
                            Longitud = -109.45999999999999,
                            Orden = 3,
                            RutaPredeterminadaId = "R7"
                        },
                        new
                        {
                            Id = 28,
                            Latitud = 27.059999999999999,
                            Longitud = -109.44,
                            Orden = 1,
                            RutaPredeterminadaId = "R8"
                        },
                        new
                        {
                            Id = 29,
                            Latitud = 27.062000000000001,
                            Longitud = -109.44499999999999,
                            Orden = 2,
                            RutaPredeterminadaId = "R8"
                        },
                        new
                        {
                            Id = 30,
                            Latitud = 27.065000000000001,
                            Longitud = -109.44799999999999,
                            Orden = 3,
                            RutaPredeterminadaId = "R8"
                        },
                        new
                        {
                            Id = 31,
                            Latitud = 27.068000000000001,
                            Longitud = -109.455,
                            Orden = 4,
                            RutaPredeterminadaId = "R8"
                        },
                        new
                        {
                            Id = 32,
                            Latitud = 27.07,
                            Longitud = -109.45999999999999,
                            Orden = 5,
                            RutaPredeterminadaId = "R8"
                        },
                        new
                        {
                            Id = 33,
                            Latitud = 27.074999999999999,
                            Longitud = -109.435,
                            Orden = 1,
                            RutaPredeterminadaId = "R9"
                        },
                        new
                        {
                            Id = 34,
                            Latitud = 27.077999999999999,
                            Longitud = -109.44,
                            Orden = 2,
                            RutaPredeterminadaId = "R9"
                        },
                        new
                        {
                            Id = 35,
                            Latitud = 27.079999999999998,
                            Longitud = -109.44499999999999,
                            Orden = 3,
                            RutaPredeterminadaId = "R9"
                        },
                        new
                        {
                            Id = 36,
                            Latitud = 27.074999999999999,
                            Longitud = -109.435,
                            Orden = 1,
                            RutaPredeterminadaId = "R10"
                        },
                        new
                        {
                            Id = 37,
                            Latitud = 27.076000000000001,
                            Longitud = -109.438,
                            Orden = 2,
                            RutaPredeterminadaId = "R10"
                        },
                        new
                        {
                            Id = 38,
                            Latitud = 27.077999999999999,
                            Longitud = -109.44199999999999,
                            Orden = 3,
                            RutaPredeterminadaId = "R10"
                        },
                        new
                        {
                            Id = 39,
                            Latitud = 27.079000000000001,
                            Longitud = -109.444,
                            Orden = 4,
                            RutaPredeterminadaId = "R10"
                        },
                        new
                        {
                            Id = 40,
                            Latitud = 27.079999999999998,
                            Longitud = -109.44499999999999,
                            Orden = 5,
                            RutaPredeterminadaId = "R10"
                        },
                        new
                        {
                            Id = 41,
                            Latitud = 27.100000000000001,
                            Longitud = -109.5,
                            Orden = 1,
                            RutaPredeterminadaId = "prueba-a-centro-1777773184083"
                        },
                        new
                        {
                            Id = 42,
                            Latitud = 27.199999999999999,
                            Longitud = -109.59999999999999,
                            Orden = 2,
                            RutaPredeterminadaId = "prueba-a-centro-1777773184083"
                        },
                        new
                        {
                            Id = 43,
                            Latitud = 27.071999999999999,
                            Longitud = -109.443,
                            Orden = 3,
                            RutaPredeterminadaId = "prueba-a-centro-1777773184083"
                        });
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.HistorialViaje", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("CostoEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DestinoLocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("DistanciaKm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FinUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InicioUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 5, 12, 7, 19, 42, 47, DateTimeKind.Utc).AddTicks(1540));

                    b.Property<string>("OrigenLocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VehiculoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DestinoLocationId");

                    b.HasIndex("OrigenLocationId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("HistorialViajes");

                    b.HasData(
                        new
                        {
                            Id = "0bbd1448-9cc9-4983-b7d2-c4fcf92bde3d",
                            DestinoLocationId = "U1",
                            Estado = "En Progreso",
                            InicioUtc = new DateTime(2026, 5, 10, 3, 5, 48, 363, DateTimeKind.Unspecified).AddTicks(7172),
                            OrigenLocationId = "prueba1-1777772764332",
                            VehiculoId = "V4"
                        },
                        new
                        {
                            Id = "2066aa6e-773a-4adf-9afd-3009c04fca3b",
                            DestinoLocationId = "U1",
                            Estado = "En Progreso",
                            InicioUtc = new DateTime(2026, 5, 10, 3, 7, 21, 533, DateTimeKind.Unspecified).AddTicks(576),
                            OrigenLocationId = "prueba1-1777772764332",
                            VehiculoId = "V2"
                        },
                        new
                        {
                            Id = "2696e4f2-da8a-495b-bd5e-ebdfe315ad65",
                            DestinoLocationId = "U1",
                            Estado = "Finalizado",
                            FinUtc = new DateTime(2026, 5, 4, 1, 23, 23, 671, DateTimeKind.Unspecified).AddTicks(7054),
                            InicioUtc = new DateTime(2026, 5, 4, 1, 23, 17, 592, DateTimeKind.Unspecified).AddTicks(3235),
                            OrigenLocationId = "prueba1-1777772764332",
                            VehiculoId = "V3"
                        },
                        new
                        {
                            Id = "310ed534-8715-48bf-8625-3d7bf61be55e",
                            DestinoLocationId = "U1",
                            Estado = "Finalizado",
                            FinUtc = new DateTime(2026, 5, 10, 3, 12, 10, 91, DateTimeKind.Unspecified).AddTicks(9828),
                            InicioUtc = new DateTime(2026, 5, 10, 3, 12, 4, 81, DateTimeKind.Unspecified).AddTicks(9988),
                            OrigenLocationId = "prueba1-1777772764332",
                            VehiculoId = "Scooter-001"
                        },
                        new
                        {
                            Id = "41f3bb58-91b8-48f3-8ebf-a79ad705bee2",
                            DestinoLocationId = "U1",
                            Estado = "Finalizado",
                            FinUtc = new DateTime(2026, 5, 10, 3, 9, 30, 691, DateTimeKind.Unspecified).AddTicks(4298),
                            InicioUtc = new DateTime(2026, 5, 10, 3, 9, 24, 598, DateTimeKind.Unspecified).AddTicks(6266),
                            OrigenLocationId = "prueba1-1777772764332",
                            VehiculoId = "Scooter-001"
                        },
                        new
                        {
                            Id = "44b42372-8330-4964-a3af-507ccedf5280",
                            DestinoLocationId = "U2",
                            Estado = "En Progreso",
                            InicioUtc = new DateTime(2026, 5, 5, 5, 58, 54, 439, DateTimeKind.Unspecified).AddTicks(6903),
                            OrigenLocationId = "U1",
                            VehiculoId = "Scooter-001"
                        },
                        new
                        {
                            Id = "4b668085-6371-45fd-9b50-431ae2d1946c",
                            DestinoLocationId = "U7",
                            Estado = "En Progreso",
                            InicioUtc = new DateTime(2026, 5, 10, 3, 3, 41, 331, DateTimeKind.Unspecified).AddTicks(1119),
                            OrigenLocationId = "U6",
                            VehiculoId = "V4"
                        },
                        new
                        {
                            Id = "611500d3-35f8-4459-87be-54b31f7680db",
                            DestinoLocationId = "U3",
                            Estado = "Finalizado",
                            FinUtc = new DateTime(2026, 5, 5, 5, 59, 56, 271, DateTimeKind.Unspecified).AddTicks(1448),
                            InicioUtc = new DateTime(2026, 5, 5, 5, 59, 50, 183, DateTimeKind.Unspecified).AddTicks(7917),
                            OrigenLocationId = "U1",
                            VehiculoId = "V1"
                        },
                        new
                        {
                            Id = "663e9a61-b4a1-4735-85bb-09ef8307b400",
                            DestinoLocationId = "U1",
                            Estado = "Finalizado",
                            FinUtc = new DateTime(2026, 5, 10, 3, 10, 57, 755, DateTimeKind.Unspecified).AddTicks(1233),
                            InicioUtc = new DateTime(2026, 5, 10, 3, 10, 51, 703, DateTimeKind.Unspecified).AddTicks(7285),
                            OrigenLocationId = "prueba1-1777772764332",
                            VehiculoId = "Scooter-001"
                        },
                        new
                        {
                            Id = "736db446-6e5f-4590-8915-9973cc423fac",
                            DestinoLocationId = "U1",
                            Estado = "Finalizado",
                            FinUtc = new DateTime(2026, 5, 5, 5, 55, 34, 500, DateTimeKind.Unspecified).AddTicks(4121),
                            InicioUtc = new DateTime(2026, 5, 5, 5, 55, 28, 397, DateTimeKind.Unspecified).AddTicks(9584),
                            OrigenLocationId = "prueba1-1777772764332",
                            VehiculoId = "V7"
                        },
                        new
                        {
                            Id = "8d3adc00-ed9e-40d9-857b-7923ff70a595",
                            DestinoLocationId = "U1",
                            Estado = "Finalizado",
                            FinUtc = new DateTime(2026, 5, 10, 3, 8, 37, 242, DateTimeKind.Unspecified).AddTicks(2646),
                            InicioUtc = new DateTime(2026, 5, 10, 3, 8, 31, 208, DateTimeKind.Unspecified).AddTicks(8291),
                            OrigenLocationId = "prueba1-1777772764332",
                            VehiculoId = "Scooter-001"
                        },
                        new
                        {
                            Id = "95a371e0-50be-4b7e-82ca-6eac04cba9e2",
                            DestinoLocationId = "U4",
                            Estado = "En Progreso",
                            InicioUtc = new DateTime(2026, 5, 10, 3, 4, 5, 590, DateTimeKind.Unspecified).AddTicks(392),
                            OrigenLocationId = "U2",
                            VehiculoId = "V3"
                        },
                        new
                        {
                            Id = "ababe30e-4aa3-4b94-ab40-e073aeb85ec3",
                            DestinoLocationId = "U1",
                            Estado = "Finalizado",
                            FinUtc = new DateTime(2026, 5, 3, 4, 55, 9, 598, DateTimeKind.Unspecified).AddTicks(6384),
                            InicioUtc = new DateTime(2026, 5, 3, 4, 55, 3, 489, DateTimeKind.Unspecified).AddTicks(3104),
                            OrigenLocationId = "prueba1-1777772764332",
                            VehiculoId = "V6"
                        },
                        new
                        {
                            Id = "af97e9e8-5176-4349-ba2f-b7089ba7bb73",
                            DestinoLocationId = "U2",
                            Estado = "Finalizado",
                            FinUtc = new DateTime(2026, 5, 5, 21, 10, 41, 690, DateTimeKind.Unspecified).AddTicks(5434),
                            InicioUtc = new DateTime(2026, 5, 5, 21, 10, 35, 545, DateTimeKind.Unspecified).AddTicks(7587),
                            OrigenLocationId = "U1",
                            VehiculoId = "V10"
                        },
                        new
                        {
                            Id = "bb8aad59-c8bd-46ca-a26e-72975825802a",
                            DestinoLocationId = "U1",
                            Estado = "Finalizado",
                            FinUtc = new DateTime(2026, 5, 3, 22, 58, 51, 78, DateTimeKind.Unspecified).AddTicks(7468),
                            InicioUtc = new DateTime(2026, 5, 3, 22, 58, 44, 995, DateTimeKind.Unspecified).AddTicks(4889),
                            OrigenLocationId = "prueba1-1777772764332",
                            VehiculoId = "V7"
                        },
                        new
                        {
                            Id = "d2b81ec5-aac7-4d7e-a165-ceb734aa5e70",
                            DestinoLocationId = "U7",
                            Estado = "Finalizado",
                            FinUtc = new DateTime(2026, 5, 10, 3, 3, 4, 612, DateTimeKind.Unspecified).AddTicks(2358),
                            InicioUtc = new DateTime(2026, 5, 10, 3, 2, 58, 508, DateTimeKind.Unspecified).AddTicks(684),
                            OrigenLocationId = "U6",
                            VehiculoId = "V7"
                        },
                        new
                        {
                            Id = "d5aba4b5-c5ea-416b-8a7a-e0825880242e",
                            DestinoLocationId = "U2",
                            Estado = "Finalizado",
                            FinUtc = new DateTime(2026, 5, 5, 7, 24, 36, 126, DateTimeKind.Unspecified).AddTicks(3108),
                            InicioUtc = new DateTime(2026, 5, 5, 7, 24, 30, 33, DateTimeKind.Unspecified).AddTicks(7935),
                            OrigenLocationId = "U1",
                            VehiculoId = "V1"
                        },
                        new
                        {
                            Id = "e1cc2e31-abf4-46c2-8105-9002c4397e5d",
                            DestinoLocationId = "U1",
                            Estado = "Finalizado",
                            FinUtc = new DateTime(2026, 5, 10, 2, 58, 37, 745, DateTimeKind.Unspecified).AddTicks(4914),
                            InicioUtc = new DateTime(2026, 5, 10, 2, 58, 31, 695, DateTimeKind.Unspecified).AddTicks(1448),
                            OrigenLocationId = "prueba1-1777772764332",
                            VehiculoId = "V10"
                        },
                        new
                        {
                            Id = "e364d369-2f88-478c-8111-1a9dc1b42632",
                            DestinoLocationId = "U5",
                            Estado = "Finalizado",
                            FinUtc = new DateTime(2026, 5, 10, 3, 2, 8, 939, DateTimeKind.Unspecified).AddTicks(746),
                            InicioUtc = new DateTime(2026, 5, 10, 3, 2, 2, 897, DateTimeKind.Unspecified).AddTicks(5135),
                            OrigenLocationId = "U3",
                            VehiculoId = "V6"
                        });
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.Pago", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("HistorialViajeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("MXN");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("HistorialViajeId");

                    b.ToTable("Pagos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "pago-1777849190243-jgftk",
                            Estado = "Completado",
                            FechaUtc = new DateTime(2026, 5, 3, 22, 59, 50, 269, DateTimeKind.Unspecified).AddTicks(5688),
                            HistorialViajeId = "bb8aad59-c8bd-46ca-a26e-72975825802a",
                            Metodo = "Efectivo",
                            Moneda = "MXN",
                            Monto = 20.13m
                        },
                        new
                        {
                            Id = "pago-1777857825020-v5edd",
                            Estado = "Completado",
                            FechaUtc = new DateTime(2026, 5, 4, 1, 23, 45, 42, DateTimeKind.Unspecified).AddTicks(7677),
                            HistorialViajeId = "ababe30e-4aa3-4b94-ab40-e073aeb85ec3",
                            Metodo = "Efectivo",
                            Moneda = "MXN",
                            Monto = 0.08m
                        },
                        new
                        {
                            Id = "pago-1777960664627-u1v2g",
                            Estado = "Completado",
                            FechaUtc = new DateTime(2026, 5, 5, 5, 57, 44, 655, DateTimeKind.Unspecified).AddTicks(7160),
                            HistorialViajeId = "2696e4f2-da8a-495b-bd5e-ebdfe315ad65",
                            Metodo = "Efectivo",
                            Moneda = "MXN",
                            Monto = 100.00m
                        });
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.RutaPredeterminada", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DestinoLocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NivelTraficoActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrigenlocationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DestinoLocationId");

                    b.HasIndex("OrigenlocationId");

                    b.ToTable("RutasPredeterminadas");

                    b.HasData(
                        new
                        {
                            Id = "prueba-a-centro-1777773184083",
                            DestinoLocationId = "U1",
                            NivelTraficoActual = 0,
                            Nombre = "Prueba a Centro",
                            OrigenlocationId = "prueba1-1777772764332"
                        },
                        new
                        {
                            Id = "R1",
                            DestinoLocationId = "U2",
                            NivelTraficoActual = 1,
                            Nombre = "Centro a Norte",
                            OrigenlocationId = "U1"
                        },
                        new
                        {
                            Id = "R10",
                            DestinoLocationId = "U7",
                            NivelTraficoActual = 2,
                            Nombre = "Hospital a Universidad ALT",
                            OrigenlocationId = "U6"
                        },
                        new
                        {
                            Id = "R2",
                            DestinoLocationId = "U2",
                            NivelTraficoActual = 2,
                            Nombre = "Centro a Norte ALT",
                            OrigenlocationId = "U1"
                        },
                        new
                        {
                            Id = "R3",
                            DestinoLocationId = "U3",
                            NivelTraficoActual = 1,
                            Nombre = "Centro a Sur",
                            OrigenlocationId = "U1"
                        },
                        new
                        {
                            Id = "R4",
                            DestinoLocationId = "U3",
                            NivelTraficoActual = 2,
                            Nombre = "Centro a Sur ALT",
                            OrigenlocationId = "U1"
                        },
                        new
                        {
                            Id = "R5",
                            DestinoLocationId = "U4",
                            NivelTraficoActual = 1,
                            Nombre = "Norte a Este",
                            OrigenlocationId = "U2"
                        },
                        new
                        {
                            Id = "R6",
                            DestinoLocationId = "U4",
                            NivelTraficoActual = 2,
                            Nombre = "Norte a Este ALT",
                            OrigenlocationId = "U2"
                        },
                        new
                        {
                            Id = "R7",
                            DestinoLocationId = "U5",
                            NivelTraficoActual = 1,
                            Nombre = "Sur a Oeste",
                            OrigenlocationId = "U3"
                        },
                        new
                        {
                            Id = "R8",
                            DestinoLocationId = "U5",
                            NivelTraficoActual = 2,
                            Nombre = "Sur a Oeste ALT",
                            OrigenlocationId = "U3"
                        },
                        new
                        {
                            Id = "R9",
                            DestinoLocationId = "U7",
                            NivelTraficoActual = 1,
                            Nombre = "Hospital a Universidad",
                            OrigenlocationId = "U6"
                        });
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.Ubicacion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Ubicaciones");

                    b.HasData(
                        new
                        {
                            Id = "prueba1-1777772764332",
                            Latitud = 27.100000000000001,
                            Longitud = -109.5,
                            Nombre = "Prueba1"
                        },
                        new
                        {
                            Id = "U1",
                            Latitud = 27.071999999999999,
                            Longitud = -109.443,
                            Nombre = "Centro"
                        },
                        new
                        {
                            Id = "U10",
                            Latitud = 27.055,
                            Longitud = -109.455,
                            Nombre = "Terminal"
                        },
                        new
                        {
                            Id = "U2",
                            Latitud = 27.085000000000001,
                            Longitud = -109.45,
                            Nombre = "Norte"
                        },
                        new
                        {
                            Id = "U3",
                            Latitud = 27.059999999999999,
                            Longitud = -109.44,
                            Nombre = "Sur"
                        },
                        new
                        {
                            Id = "U4",
                            Latitud = 27.07,
                            Longitud = -109.42,
                            Nombre = "Este"
                        },
                        new
                        {
                            Id = "U5",
                            Latitud = 27.07,
                            Longitud = -109.45999999999999,
                            Nombre = "Oeste"
                        },
                        new
                        {
                            Id = "U6",
                            Latitud = 27.074999999999999,
                            Longitud = -109.435,
                            Nombre = "Hospital"
                        },
                        new
                        {
                            Id = "U7",
                            Latitud = 27.079999999999998,
                            Longitud = -109.44499999999999,
                            Nombre = "Universidad"
                        },
                        new
                        {
                            Id = "U8",
                            Latitud = 27.065000000000001,
                            Longitud = -109.43000000000001,
                            Nombre = "Parque"
                        },
                        new
                        {
                            Id = "U9",
                            Latitud = 27.073,
                            Longitud = -109.438,
                            Nombre = "Plaza"
                        });
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.Vehiculo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Combustible")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UltimaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 5, 12, 7, 19, 42, 46, DateTimeKind.Utc).AddTicks(3416));

                    b.HasKey("Id");

                    b.ToTable("Vehiculos");

                    b.HasData(
                        new
                        {
                            Id = "Scooter-001",
                            Combustible = 88,
                            Estado = "Disponible",
                            Latitud = 27.071999999999999,
                            Longitud = -109.443,
                            Tipo = "Scooter",
                            UltimaActualizacion = new DateTime(2026, 5, 10, 3, 12, 10, 48, DateTimeKind.Unspecified).AddTicks(8365)
                        },
                        new
                        {
                            Id = "Scooter-002",
                            Combustible = 88,
                            Estado = "Disponible",
                            Latitud = 27.077999999999999,
                            Longitud = -109.44799999999999,
                            Tipo = "Scooter",
                            UltimaActualizacion = new DateTime(2026, 5, 10, 3, 11, 52, 587, DateTimeKind.Unspecified).AddTicks(2180)
                        },
                        new
                        {
                            Id = "V1",
                            Combustible = 47,
                            Estado = "Disponible",
                            Latitud = 27.085000000000001,
                            Longitud = -109.45,
                            Tipo = "Auto",
                            UltimaActualizacion = new DateTime(2026, 5, 10, 3, 11, 52, 27, DateTimeKind.Unspecified).AddTicks(798)
                        },
                        new
                        {
                            Id = "V10",
                            Combustible = 43,
                            Estado = "Disponible",
                            Latitud = 27.071999999999999,
                            Longitud = -109.443,
                            Tipo = "Camion",
                            UltimaActualizacion = new DateTime(2026, 5, 10, 3, 11, 52, 612, DateTimeKind.Unspecified).AddTicks(9546)
                        },
                        new
                        {
                            Id = "V2",
                            Combustible = 57,
                            Estado = "Disponible",
                            Latitud = 27.085000000000001,
                            Longitud = -109.45,
                            Tipo = "Moto",
                            UltimaActualizacion = new DateTime(2026, 5, 10, 3, 11, 52, 642, DateTimeKind.Unspecified).AddTicks(4875)
                        },
                        new
                        {
                            Id = "V3",
                            Combustible = 44,
                            Estado = "Disponible",
                            Latitud = 27.071999999999999,
                            Longitud = -109.443,
                            Tipo = "Auto",
                            UltimaActualizacion = new DateTime(2026, 5, 10, 3, 11, 52, 396, DateTimeKind.Unspecified).AddTicks(542)
                        },
                        new
                        {
                            Id = "V4",
                            Combustible = 90,
                            Estado = "Disponible",
                            Latitud = 27.07,
                            Longitud = -109.42,
                            Tipo = "Camion",
                            UltimaActualizacion = new DateTime(2026, 5, 10, 3, 11, 52, 505, DateTimeKind.Unspecified).AddTicks(2411)
                        },
                        new
                        {
                            Id = "V5",
                            Combustible = 67,
                            Estado = "Disponible",
                            Latitud = 27.071999999999999,
                            Longitud = -109.443,
                            Tipo = "Auto",
                            UltimaActualizacion = new DateTime(2026, 5, 10, 3, 11, 52, 545, DateTimeKind.Unspecified).AddTicks(4565)
                        },
                        new
                        {
                            Id = "V6",
                            Combustible = 34,
                            Estado = "Disponible",
                            Latitud = 27.07,
                            Longitud = -109.45999999999999,
                            Tipo = "Moto",
                            UltimaActualizacion = new DateTime(2026, 5, 10, 3, 11, 52, 285, DateTimeKind.Unspecified).AddTicks(467)
                        },
                        new
                        {
                            Id = "V7",
                            Combustible = 76,
                            Estado = "Disponible",
                            Latitud = 27.079999999999998,
                            Longitud = -109.44499999999999,
                            Tipo = "Auto",
                            UltimaActualizacion = new DateTime(2026, 5, 10, 3, 11, 52, 476, DateTimeKind.Unspecified).AddTicks(5969)
                        },
                        new
                        {
                            Id = "V8",
                            Combustible = 30,
                            Estado = "Disponible",
                            Latitud = 27.065000000000001,
                            Longitud = -109.43000000000001,
                            Tipo = "Moto",
                            UltimaActualizacion = new DateTime(2026, 5, 10, 3, 11, 52, 674, DateTimeKind.Unspecified).AddTicks(4411)
                        },
                        new
                        {
                            Id = "V9",
                            Combustible = 74,
                            Estado = "Disponible",
                            Latitud = 27.071999999999999,
                            Longitud = -109.443,
                            Tipo = "Auto",
                            UltimaActualizacion = new DateTime(2026, 5, 10, 3, 11, 52, 373, DateTimeKind.Unspecified).AddTicks(4271)
                        });
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.Coordenada", b =>
                {
                    b.HasOne("MovilidadInteligente.Domain.Entities.RutaPredeterminada", "RutaPredeterminada")
                        .WithMany("Coordenadas")
                        .HasForeignKey("RutaPredeterminadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RutaPredeterminada");
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.HistorialViaje", b =>
                {
                    b.HasOne("MovilidadInteligente.Domain.Entities.Ubicacion", "DestinoLocation")
                        .WithMany()
                        .HasForeignKey("DestinoLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovilidadInteligente.Domain.Entities.Ubicacion", "OrigenLocation")
                        .WithMany()
                        .HasForeignKey("OrigenLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovilidadInteligente.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinoLocation");

                    b.Navigation("OrigenLocation");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.Pago", b =>
                {
                    b.HasOne("MovilidadInteligente.Domain.Entities.HistorialViaje", "HistorialViaje")
                        .WithMany()
                        .HasForeignKey("HistorialViajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Pagos_HistorialViajes");

                    b.Navigation("HistorialViaje");
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.RutaPredeterminada", b =>
                {
                    b.HasOne("MovilidadInteligente.Domain.Entities.Ubicacion", "DestinoLocation")
                        .WithMany()
                        .HasForeignKey("DestinoLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovilidadInteligente.Domain.Entities.Ubicacion", "OrigenlLocation")
                        .WithMany()
                        .HasForeignKey("OrigenlocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinoLocation");

                    b.Navigation("OrigenlLocation");
                });

            modelBuilder.Entity("MovilidadInteligente.Domain.Entities.RutaPredeterminada", b =>
                {
                    b.Navigation("Coordenadas");
                });
#pragma warning restore 612, 618
        }
    }
}
